//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelFileProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public country()
        {
            this.masters = new HashSet<master>();
        }
    
        public int id { get; set; }
        public string countries { get; set; }
        public string countryCodes { get; set; }
        public Nullable<int> region_id { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<int> fundSymbol_id { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual fundSymbol fundSymbol { get; set; }
        public virtual region region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master> masters { get; set; }
    }
}
