//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelFileProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class master
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<double> portfolioWeight { get; set; }
        public Nullable<double> effectiveDuration { get; set; }
        public Nullable<double> embeddedIncomeYield { get; set; }
        public Nullable<double> yieldToMaturity { get; set; }
    
        public virtual country country { get; set; }
    }
}
